@Host = http://localhost:3333
@AuthToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{Host}}/accounts
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johndoe@example23.com",
  "password": "123456"
}

### 

# @name authenticate
POST {{Host}}/sessions
Content-Type: application/json

{
  "email": "johndoe@example23.com",
  "password": "123456" 
}

###

# @name create_question

POST {{Host}}/questions
Authorization: Bearer {{AuthToken}}
Content-Type: application/json

{
  "title": "New Question 2",
  "content": "This is a new question 2."
}

###

# @name fetch_recent_questions

GET {{Host}}/questions
Authorization: Bearer {{AuthToken}}
Content-Type: application/json
